import type { NextPage } from "next";
import Head from "next/head";
import HomeSection from "../components/modules/Home";
import WorkSection from "../components/modules/Work";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NextJs App</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSection />
      <WorkSection />
    </>
  );
};

export default Home;
