import type { NextPage } from "next";
import Head from "next/head";
import img from "../public/images/portfolio-img1.jpg";
import HomeSection from "../components/modules/Home";
import WorkSection from "../components/modules/Work";
import AboutSection from "../components/modules/About";
import PostFolioSection from "../components/modules/PostFolio";
import ContactSection from "../components/modules/Contact";
import CopyRightSection from "../components/modules/CopyRight";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NextJs App</title>
        <meta name="description" content="Generated by next app" />
        <meta property="og:image" content={`${img}`} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSection />
      <WorkSection />
      <AboutSection />
      <PostFolioSection />
      <ContactSection />
      <CopyRightSection />
    </>
  );
};

export default Home;
